VPS-131/adding self to contributors readme (John)
UoaWDCC/VPS pull request #140
Opened 2024-03-21 23:24 UTC by codecreator127

## Describe the issue

John's profile missing from ReadMe contributor's list

## Describe the solution

Added John to the ReadMe contributor's list by copying existing table data and editing the profile image and names. Put next to Tech Lead Woo-Jin's profile.

## Risk

Potential merging conflicts

## Definition of Done

- [ ] Code peer-reviewed
- [ ] Acceptance criteria met

## Reviewed By

Who reviewed your PR - for commit history once merged

2024-03-21 23:30 UTC, JordanBlenn requested changes
Good - I would prefer you remove the lock files from the PR just in terms of simplicity, but it shouldn't really change the functionality of the code as they get regenerated anyways (see other comments).

2024-03-21 23:30 UTC, JordanBlenn commented on yarn.lock
The `package.json`, `package-lock.json`, and `yarn.lock` should be regenerated every time you run `yarn run init` (I believe), so you shouldn't need to commit them.

2024-03-21 23:30 UTC, JordanBlenn commented on README.md
Looks good :)

2024-03-23 10:44 UTC, codecreator127 commented on yarn.lock
will remove them. Going to add those to the gitignore to avoid future such issues

2024-03-23 10:51 UTC, JordanBlenn approved these changes
All good

2024-03-23 22:54 UTC, closed without merging