VPS-029/Lecturer Authentication for Dashboard
UoaWDCC/VPS pull request #42
Opened 2022-09-08 03:12 UTC by lia-arroyo

## Describe the issue

Dashboard should only be viewed by lecturers, but is currently accessible to everyone

## Describe the solution

Create a page that’s only accessible to lecturers when they log in where they can see the dashboard (and other students can't access it when they log in)

## Risk

Low (potentially security risk?)

## Definition of Done

- [ ] Code peer-reviewed
- [ ] Wiki Documentation is written and up to date
- [ ] Unit tests written and passing
- [ ] Integration tests written and passing
- [ ] Continuous Integration build passing
- [ ] Acceptance criteria met
- [ ] Deployed to production environment

## Reviewed By

Who reviewed your PR - for commit history once merged

2022-09-08 06:08 UTC, lia-arroyo commented
Hey team, 

I managed to bring my authentication to the backend. I also changed to check for firebase ID instead of an email address for extra security.

I tried fixing all the failing tests, but I can't seem to fix the backend test. It's to do with unhandled errors and possibly promises, but I don't know how to fix them :(

2022-09-08 06:14 UTC, DamonGreenhalgh commented
Yeah I had the exact same problem with my PR. It might have been introduced in a previous sprint. 

![image](https://user-images.githubusercontent.com/59471444/189047751-076941c9-ca63-48dc-919a-4608ba37c19a.png)

Maybe it requires a type check before the `push` method?

2022-09-08 08:43 UTC, nickykay98 commented
Doesn't say there are any conflicts with main + the error seems to be with the scene/scenario durations (mb some of the timer work that other people did) so your stuff shouldn't be impacted I think? 

Lmk if y'all are working on passing the unit test though or if you think it's a more serious issue, could ask someone who worked on scenarioDao.js to look into it

2022-09-09 13:13 UTC, Ray-F requested changes
Hey @lia-arroyo, awesome work on getting on with this hefty task that requires some real thinking all across the entire stack, from firebase, Mongo, frontend to backend! I've left a few comments around your code, mostly just cosmetic and best practice sort of things.

The main thing is around the /staff endpoint, and I've left that in a comment about that which you can look at. Let me know if anything doesn't make sense and happy to chat more about it on Slack.

2022-09-09 13:13 UTC, Ray-F commented on backend/src/routes/api/staff.js
> +  const staff = await retrieveAuthorisedStaffList();
You should do some processing here on this line (9) so that you don't return the entire staff list. For example, your database may have information about the staff's firebaseID and emailAddress, but you may only want to return their email address (or firebase ID). Even if you do want to return all the data inside the model, it's still good practice to wrap it a bit, something like.

const staffModel = await retrieveAuthorisedStaffList();

```
const staffDto = {
  email: staffModel.emailAddress,
  firebaseId: staffModel.firebaseID,
};
```

That way, if your database models change, this won't impact your frontend (and keeps them decoupled).

2022-09-09 13:13 UTC, Ray-F commented on backend/src/routes/api/staff.js
> +const HTTP_OK = 200;
Nice work on taking this constant out! 👍 

Depending on whether it's used somewhere else, it could be worth having an entire file dedicated to HTTP status codes, like

```
// http.status.js

export const HttpStatusCode = {
  OK: 200,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
  // etc
}
```

Might be worth discussing with @Harshal-D and @nickykay98 if this would be a new story, but definitely not a priority

2022-09-09 13:13 UTC, Ray-F commented on frontend/src/hooks/crudHooks.js
> +export function useGetSimplified(url, setData) {
Was there a reason why you couldn't use the defined `useGet()` for this as well? That way we don't need to rewrite some of the axios logic again

2022-09-09 13:13 UTC, Ray-F commented on frontend/src/firebase/ProtectedRoute.js
> +function ProtectedRoute({ children, accessLevel = "user", ...rest }) {
You can take the constant `"user"` out into some other file, similar to the HttpStatusCode thing in the backend

```
// route.access.level.js

export const AccessLevel {
  USER: "user",
  ADMIN: "admin",
}
```

2022-09-09 13:13 UTC, Ray-F commented on frontend/src/firebase/ProtectedRoute.js
> +          if (VpsUser.role === accessLevel || accessLevel === "user") {
Why is the accessLevel === "user" check needed here? Should all logged in users by default have the `VpsUser.role` set to `"user"`?

2022-09-09 13:13 UTC, Ray-F commented on backend/src/routes/api/staff.js
> +router.get("/", async (req, res) => {
I think a better approach for this endpoint may be to have it as you pass in a firebase ID, and it returns the email address and role associated with that firebase ID. That way (1) you don't expose the emails of all admins via this route (which isn't really safe) and (2) the role is determined by the API, and not by the frontend logic. Otherwise, you would need to create an endpoint for each type of access level.

The query signature (in its entirety) could be something like:

`.../auth/:firebaseId`

and returns an object like:

```
{
  firebaseId: string,
  role: "staff" | "user"
}
```

If there is no corresponding user in the staff list, it could be default set to "user".

Changing this API endpoint may require a few changes in your frontend logic as well, but I definitely think this is an important change

2022-09-09 13:13 UTC, Ray-F commented on frontend/src/context/AuthenticationContextProvider.js
> +      return "user";
This role setting should happen on the backend (see the previous comment on the router.get() method)

2022-09-09 13:13 UTC, Ray-F commented on frontend/src/context/AuthenticationContextProvider.js
> +        }
Once this code is moved to the backend, something you could do is use the javascript `[].includes()` method. This can be used like so:

```
const isStaff = staffList.includes(user.uid);
```

(Side note: in general there's a lot of functional methods on arrays in Java, C#, javascript, python etc that allow you to do most things without a for loop, such as `.map(), .includes(), .find()` in JS, that make your code more expressive. Another huge benefit of this is that you can avoid declaring variables with "let" and instead as constants, as having modifiable variables is often a source of bugs).

2022-09-13 12:17 UTC, lia-arroyo commented on backend/src/routes/api/staff.js
> +const HTTP_OK = 200;
Yeah, these HTTP status codes are used in the other files in the backend > src > routes > api folder. 

Could be a task for the future.

2022-09-13 12:30 UTC, lia-arroyo commented on frontend/src/hooks/crudHooks.js
> +export function useGetSimplified(url, setData) {
I was getting this error when using the useGet: 
![image](https://user-images.githubusercontent.com/94775011/189899293-b0756c44-c3e5-4b9b-8326-600b0d2cc243.png)

I suspected it was something to do with the getUserIdToken being used in both useGet hook and the Authentication Context, but I didn't want to change the useGet and the method in Authentication Context directly. 

However, I think this issue will be resolved when I move some logic to the backend and will make some changes once I've done that :)

2022-10-05 09:55 UTC, lia-arroyo commented on frontend/src/firebase/ProtectedRoute.js
> +          if (VpsUser.role === accessLevel || accessLevel === "user") {
Yep, you are right, all logged in users by default should have VpsUser.role set to "user". 

I've changed the variable name as this old name was a bit misleading, but this variable is for the access level required for a page/protected route. I believe this check is needed as currently, any logged-in user that is considered a "staff" wouldn't be able to access any routes that just have the "user" access level required. 

There is probably a better way to implement this hierarchy of roles in the future, especially if we decide to have more roles.

2022-10-05 10:23 UTC, lia-arroyo commented
Hi @Ray-F ! Thanks so much for your helpful comments! 

Apologies for the slow reply, but after finding some time and learning some more MongoDB, I have finally made some decent progress on your feedback.  

I've modified the code, so now:

1. In the AuthenticationContext, there is a VpsUser object that contains both the firebase user object and its role.
2. The firebase ID is passed into the backend endpoint, and it returns a list of MongoDB documents (from the staffs collection) associated with that firebase ID. 
3. The role is then determined by that list in 2^, and this role is passed back to the frontend (didn't need to pass back any other information as we already have this from the firebase user obj) 
4. This role is updated and can be accessed through the VpsUser object

I've also taken out the constants for the different access levels into a separate file. 

Hopefully that would have improved the major security concerns, but please let me know if you have more feedback!

The only thing I haven't resolved is the custom useGet hook, as I keep getting this error related to the getUserIdToken. So atm, it works with the useGetSimplified only. @DamonGreenhalgh have you come across this by any chance?
![image](https://user-images.githubusercontent.com/94775011/194037577-9c12bcb7-15e5-4e04-b7a8-a300016096fc.png)

Thank you :)

2022-10-08 21:58 UTC, Ray-F requested changes
Hey Lia, awesome and it's looking really good now! Just noticed a tiny one around the `AccessLevel` enum not being used in a place, but should be an easy fix :). I think once that's changed this can be merged in

2022-10-08 21:58 UTC, Ray-F commented on frontend/src/components/SideBar.js
> +          {VpsUser.role === "admin" ? (
`AccessLevel.STAFF` instead of `"admin"` here

2022-10-08 21:58 UTC, Ray-F commented on frontend/src/hooks/crudHooks.js
> +export function useGetSimplified(url, setData) {
All good! 

Yes I think looking into it more the `useGet()` that was previously defined by the prev team probably was more an `useAuthenticatedGet()` and some of the functionality probably wasn't needed for your endpoint. I think `useSimplifiedGet()` method for now is good 👍

2022-10-10 23:43 UTC, lia-arroyo commented
Sweet, thank you for reviewing it, Ray! 

I've updated the Sidebar component to use the AccessLevel enum now. Thanks for spotting that :)

2022-10-10 23:56 UTC, merged